#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jan 27 18:35:15 2022
"""

import random
numbs=random.randint(1, 120)
guess=None
# line 13 contains the prizes that the computer will make a choice from the list and display it when the computer has hit the lucky number 
prizes=["New Mexico","Airizona",'California','Orgeon','Washigtion','Idaho''Hawaii','Montana','South Dokota','North Dakota',"South Africa",'Dubai',"Doha","france","london",'Beliguim',"Conzumel,mex","mazatlan,sinaloa","los Mochis","Mexico City"]
prize_picker=random.choice(prizes)
while guess != numbs:
 guess=int(input("\n im thinking about a number from 1 to 120 what number im i thinking: "))
 if guess == int(numbs):# the program will convert the input number to a int
  print(f"congratulations you have won a free trip to \n {prize_picker} for guessing the number have fun")
  break
 elif guess > numbs:
        print("You guessed too small!")
 elif guess < numbs:
        print("You Guessed too high!")
#notes for the program

#line 16 is where the user will input the guessing number 
# lines 20 to 23 are statements that prompt the user with the guess was high or too low! 
